
PHONY := __clean
__clean:

include scripts/Makefile.include

__clean: $(libdir) $(objdir)
	$(call cmd,cleanfiles)

$(libdir) $(objdir):
	$(Q)$(MAKE) $(clean)=$@

PHONY += $(libdir) $(objdir)

.PHONY: $(PHONY)
