
PHONY := __genjs
__genjs:

include scripts/Makefile.include

__genjs: $(subdir) $(obj) $(lib)
	@:

$(subdir):
	$(Q)$(MAKE) $(genjs)=$@

$(dst)/%.o: $(src)/%.c FORCE
	$(call cmd,gencmd)

FORCE:

PHONY += $(subdir) FORCE

.PHONY: $(PHONY)
