
PHONY := __clean
__clean :


include scripts/Makefile.include


# Clean
# ---------------------------------------------------------------------------
clean_files := $(obj) $(obj_deps) $(single) $(multi) \
		$(lib) $(lib_deps) $(curlib) $(arlib) $(shlib)

echo_clean = CLEAN   $(src)
cmd_clean = rm -rf $(clean_files)


__clean : $(subdir)
	$(call cmd,clean)

$(subdir) :
	$(Q)$(MAKE) $(clean)=$@


PHONY += $(subdir)

.PHONY: $(PHONY)
