
PHONY := __bininst
__bininst :


include scripts/Makefile.include


# Install bin
# ---------------------------------------------------------------------------
inst_bindir := $(inst_path)/bin
inst_bin    := $(single) $(multi)

echo_bininst = INSTALL $@
cmd_bininst = mkdir -p $(inst_bindir); cp -r $@ $(inst_bindir)


__bininst : $(subdir) $(inst_bin)
	@:

$(subdir) :
	$(Q)$(MAKE) $(bininst)=$@

$(inst_bin) :
	$(call cmd,bininst)


PHONY += $(subdir) $(inst_bin)

.PHONY: $(PHONY)
